version: 2

models:
  - name: stg_sales
    description: "Cleaned and standardized sales data"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
      - name: amount
        tests:
          - not_null
