lakehouse_mvp:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /workspace/db/lakehouse.duckdb
      schema: staging
      threads: 4
      extensions:
        - iceberg
      settings:
        unsafe_enable_version_guessing: true
